=== cco2bach-bit/Proyecto-Intermodular-Jaime-Bernardino-Asier-Brutman-1-ASIR/Proyecto Intermodular (Lenguaje de marcas)/XML2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="precio">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="moneda" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="categoria" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cco2bach-bit/Proyecto-Intermodular-Jaime-Bernardino-Asier-Brutman-1-ASIR/Proyecto Intermodular (Lenguaje de marcas)/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML2.xsd">
    <producto categoria="CPU">
        <id>CPU-001</id>
        <nombre>Intel Core i9-12900KF</nombre>
        <precio moneda="EUR">310.00</precio>
        <descripcion>Potencia híbrida de alto rendimiento para gaming y cargas exigentes.</descripcion>
    </producto>

    <producto categoria="GPU">
        <id>GPU-001</id>
        <nombre>ASUS TUF Gaming GeForce RTX 4070 SUPER</nombre>
        <precio moneda="EUR">650.00</precio>
        <descripcion>Tarjeta gráfica de gama alta equilibrada con excelente refrigeración.</descripcion>
    </producto>

    <producto categoria="RAM">
        <id>RAM-001</id>
        <nombre>Corsair Vengeance 32GB DDR5 5600MHz</nombre>
        <precio moneda="EUR">120.00</precio>
        <descripcion>Memoria DDR5 de alto rendimiento y baja latencia.</descripcion>
    </producto>
</catalogo>
